# edited version of call_cnvr from HandyCNV
# this version supports .rawcnv files split into only duplications or deletions

call_cnvr2 <- function (clean_cnv, roh = NULL, chr_set = 29, folder = "UMD") 
{
  if (!file.exists(folder)) {
    dir.create(folder)
    cat(paste0("Output folder '", folder, "' was created in the working directory.\n"))
  }
  if (typeof(clean_cnv) == "character") {
    clean_cnv <- data.table::fread(file = clean_cnv, sep = "\t", 
                                   header = TRUE)
  } else {
    clean_cnv = clean_cnv
  }
  check_colnames <- c("Sample_ID", "Chr", "Start", "End", "CNV_Value", 
                      "Length")
  if (!all(check_colnames %in% names(clean_cnv))) {
    cat("Lack of necessary information. The input file shoud have at least five columns as follows:")
    print(check_colnames)
    stop("Standard input file should be generated by the 'clean_cnv' function!")
  }
  merge_cnvr <- function(cnv) {
    if (nrow(cnv) == 1) {
      return(cnv)
    }
    cnv <- cnv[order(cnv$Chr, cnv$Start), ]
    cnvr_union = cnv[1, ]
    for (i in 2:nrow(cnv)) {
      rest_cnv <- cnv[i, ]
      if (cnvr_union$End[nrow(cnvr_union)] < rest_cnv$Start) {
        cnvr_union <- bind_rows(cnvr_union, rest_cnv)
      }
      else if (cnvr_union$End[nrow(cnvr_union)] == rest_cnv$Start) {
        cnvr_union$End[nrow(cnvr_union)] <- rest_cnv$End
      }
      if (rest_cnv$End > cnvr_union$End[nrow(cnvr_union)]) {
        cnvr_union$End[nrow(cnvr_union)] <- rest_cnv$End
      }
    }
    return(cnvr_union)
  }
  cnvr <- data.frame()
  for (i in 1:chr_set) {
    cnv_chr <- clean_cnv[which(clean_cnv$Chr == i), ]
    cnvr_chr <- merge_cnvr(cnv = cnv_chr)
    cnvr <- rbind(cnvr, cnvr_chr)
    print(paste0("Chromosome ", i, " has been processed."))
  }
  cnvr_union <- cnvr[, c("Chr", "Start", "End")]
  cnvr_union$CNVR_ID <- paste0("CNVR_", seq(1, nrow(cnvr_union), 
                                            1))
  cnvr_union <- setDT(cnvr_union)
  clean_cnv <- setDT(clean_cnv)
  data.table::setkey(cnvr_union, Chr, Start, End)
  cnv_cnvr <- data.table::foverlaps(clean_cnv, cnvr_union)
  names(cnv_cnvr)[names(cnv_cnvr) == "i.Start"] <- "CNV_Start"
  names(cnv_cnvr)[names(cnv_cnvr) == "i.End"] <- "CNV_End"
  cnvr_frequency <- cnv_cnvr %>% group_by(CNVR_ID) %>% dplyr::summarize(Frequency = n(), 
                                                                        n_Sample = length(unique(Sample_ID)))
  cnvr_union_f <- merge(cnvr_union, cnvr_frequency, by = "CNVR_ID", 
                        sort = F)
  fwrite(cnvr_union_f, file = paste0(folder, "/no_freq_cnvr.txt"), 
         sep = "\t", quote = FALSE)
  if (is.null(roh)) {
    cnvr_type <- cnv_cnvr %>% group_by(CNVR_ID) %>% dplyr::count(CNV_Value, 
                                                                 name = "Count")
    cnvr_type2 <- reshape2::dcast(cnvr_type, CNVR_ID ~ CNV_Value, 
                                  value.var = "Count")
    cnvr_type2$Type <- NA
    for (i in 1:nrow(cnvr_type2)) 
    {
      
      if( all(c("0","1")  %in% colnames(cnvr_type2)))
      {
        
        cnvr_type2$Type[i] <- "Loss"
        
      }
      
      if( all(c("3","4")  %in% colnames(cnvr_type2)))
      {
        
        cnvr_type2$Type[i] <- "Gain"
        
      }
      
    }
    cnvr_f_type <- merge(cnvr_union_f, cnvr_type2, sort = F)
    cnvr_f_type$Length <- cnvr_f_type$End - cnvr_f_type$Start + 
      1
    cat(paste0(nrow(cnvr_f_type), " CNVRs generated in total.\n"))
    cnvr_summary <- cnvr_f_type %>% group_by(Type) %>% dplyr::summarise(N = dplyr::n(), 
                                                                        `Average Length` = mean(Length), `Min Length` = min(Length), 
                                                                        `Max Length` = max(Length), `Total Length` = sum(Length))
    cnvr_chr_summary <- cnvr_f_type %>% group_by(Chr) %>% 
      dplyr::summarise(`Total Length` = sum(Length), `Number of CNVR` = dplyr::n())
    cat("Overall summary of CNVRs:\n")
    print(cnvr_summary)
    cat("Summary of CNVRs on each Chromosome:\n")
    print(cnvr_chr_summary)
    fwrite(cnv_cnvr, file = paste0(folder, "/individual_cnv_cnvr.txt"), 
           sep = "\t", quote = FALSE)
    fwrite(cnvr_f_type, file = paste0(folder, "/cnvr.txt"), 
           sep = "\t", quote = FALSE)
    fwrite(cnvr_summary, file = paste0(folder, "/cnvr_summary.txt"), 
           sep = "\t", quote = FALSE, col.names = TRUE)
    fwrite(cnvr_chr_summary, file = paste0(folder, "/cnvr_chr_summary.txt"), 
           sep = "\t", quote = FALSE, col.names = TRUE)
    return(cnvr_f_type)
    if (file.exists(paste0(folder, "/cnvr.txt")) & file.exists(paste0(folder, 
                                                                      "/individual_cnv_cnvr.txt"))) {
      cat(paste0("Task done, CNVR results were saved in the '", 
                 folder, "' directory.\n"))
    }
    else {
      warning("No output file produced. Please check the format of your input file!!")
    }
  }
  else {
    cnvr_union_f$length <- cnvr_union_f$End - cnvr_union_f$Start + 
      1
    fwrite(cnvr_union_f, file = paste0("call_cnvr_", folder, 
                                       "/roh.txt"), sep = "\t", quote = FALSE)
    if (file.exists(paste0(folder, "/roh.txt"))) {
      cat(paste0("Task done, ROH results saved in the '", 
                 folder, "' directory.\n"))
    }
    else {
      warning("No output file produced. Please check the format of your input file!!")
    }
  }
}